import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import selection from './public/offer-selection.js';
async function panel(){const elements={},el=id=>elements[id]||={value:'',textContent:'',innerHTML:'',hidden:true,disabled:false,addEventListener(){},focus(){}};const storage=new Map();const code=(await readFile(new URL('./public/index.html',import.meta.url),'utf8')).split('<script>')[1].split('</script>')[0].replace(/init\(\);\s*$/,'');const ctx={limitOffers:selection.limitOffers,document:{getElementById:el,createElement(){return {remove(){}}},head:{append(){}}},window:{open(){throw Error('Não deve abrir outra página')}},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},console,URL,Date,AbortSignal,setTimeout:()=>1,clearTimeout(){},Blob};vm.createContext(ctx);vm.runInContext(code,ctx);vm.runInContext(`load([['AGRUPADOR','DESCRIÇÃO DO PRODUTO','MARCA','SEXO','GRUPO','CUSTO','PRECO DE VENDA'],['CORRE5U','CORRE 5 U PRETO 40','OLYMPIKUS','U','TENIS',250,599.99],['JOLT5M','JOLT 5 M','ASICS','M','TENIS',150,299.99]],'Teste')`,ctx);el('search').value='Corre 5';vm.runInContext('filter()',ctx);return {ctx,el,storage}}
test('botão sem serviço não abre GitHub nem simula consulta concluída',async()=>{const {ctx,el}=await panel();await vm.runInContext('requestInternet()',ctx);assert.match(el('marketNotice').textContent,/ainda não foi ativada/)});
test('botão faz POST somente do agrupador selecionado e mostra preços no painel',async()=>{const {ctx,el}=await panel();let request;ctx.fetch=async(url,options)=>{request={url,...options};return {ok:true,json:async()=>({offers:[{source:'Netshoes',category:'marketplace',price:590,currency:'BRL',match:true,url:'https://www.netshoes.com.br/p/corre',checkedAt:new Date().toISOString(),title:'Tênis Olympikus Corre 5'}],sources:[],requestedAt:new Date().toISOString()})}};vm.runInContext("settings.marketEndpoint='https://service.test/consultar'",ctx);el('accessCode').value='owner-code';await vm.runInContext('requestInternet()',ctx);assert.equal(request.url,'https://service.test/consultar');assert.equal(request.method,'POST');assert.deepEqual(JSON.parse(request.body),{brand:'OLYMPIKUS',group:'CORRE5U'});assert.match(el('offers').innerHTML,/590,00/);assert.match(el('marketNotice').textContent,/Consulta concluída/);assert.equal(el('analyze').disabled,false)});
test('falha do serviço mantém ofertas anteriores e informa erro',async()=>{const {ctx,el}=await panel();vm.runInContext("settings.marketEndpoint='https://service.test/consultar'",ctx);el('accessCode').value='owner-code';el('offers').innerHTML='resultado anterior';ctx.fetch=async()=>({ok:false,json:async()=>({error:'Serviço indisponível'})});await vm.runInContext('requestInternet()',ctx);assert.equal(el('offers').innerHTML,'resultado anterior');assert.equal(el('marketNotice').textContent,'Serviço indisponível')});

test('seletor oficial envia a restrição ao serviço sem abrir outra página',async()=>{const {ctx,el}=await panel();let body;ctx.fetch=async(url,options)=>{body=JSON.parse(options.body);return {ok:true,json:async()=>({offers:[],sources:[]})}};vm.runInContext("settings.marketEndpoint='https://service.test/consultar'",ctx);el('sourceMode').value='official';el('accessCode').value='owner-code';await vm.runInContext('requestInternet()',ctx);assert.deepEqual(body,{brand:'OLYMPIKUS',group:'CORRE5U',scope:'official'})});
